### ISSUE TITLE
Doesn't block Amazon.com

### ISSUE THREAD

**Issue by BillH99999** [gregsadetsky/chrome-dont-add-custom-search-engines#34] opened 2020-08-12 22:02 UTC
When I do a search on Amazon.com then it gets added to the custom search engines in Chrome.  Shouldn't this extension block that?

This is what was added.

https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=%s

Thanks,
Bill

**Comment by cxw42** [comment] 2020-08-13 01:43
Bill, thanks for reporting!  Would you please tell us the steps you took, in order, while searching?  Desktop or mobile interface to Amazon?  Which search box?  Which URL?  Which Chrome and extension version?  If we can reproduce what you are experiencing, we will have a much better chance of fixing it.  Thank you!

Chris

**Comment by BillH99999** [comment] 2020-08-18 15:56
I went to Amazon.com, https://www.amazon.com,  on my desktop running Windows 10 1909.  I am using Google Chrome version  84.0.4147.125 (Official Build) (64-bit).  I am using the extension version 0.0.6.

I use the main search window at the top and search for something.  After doing the search, amazon.com is added to the custom search engine list (see attached).  Expanding the URL gives this:  https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=%s

![image1](https://user-images.githubusercontent.com/26846819/90536206-97d1a480-e130-11ea-884b-7bcdc3bab816.jpg)

The same thing happened on costco.com.

**Comment by Powerbored** [comment] 2020-09-19 13:51
I couldn't reproduce this on https://www.amazon.com/, https://www.costco.com/, or https://www.twitch.tv/ (I'd experienced something similar in the past).
Google Chrome: Version 85.0.4183.83 (Official Build) (64-bit)
Extension: 0.0.6
Windows: 10 Pro, 1903

**Comment by BillH99999** [comment] 2020-09-19 15:14
I seem to be experiencing it randomly.  Sometimes they are added to the search engines in Chrome and sometimes the aren't.  I have now gone for about a month without any being added.

Bill

**Comment by BillH99999** [comment] 2020-10-17 04:13
Now I have gone another month and still none have been entered.  Don't know what was happening before, but it seem to be working fine now.

**Comment by cxw42** [comment] 2020-10-18 18:42
Bill, glad to hear it!  Amazon has probably been changing their underlying code.  Or maybe you were caught in an A/B test they ran.  I'm going to close this issue for now, but please feel free to re-open if the issue pops up again.  Thanks for keeping us up to date on the status!

**Closed by cxw42** 2020-10-18 18:42 UTC
Labels: site-specific
